"""seed initial schema

Revision ID: c4c8dee91871
Revises: 
Create Date: 2026-09-01 12:27:05.203564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4c8dee91871'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('original_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_created_at', 'stories', ['created_at'], unique=False)
    op.create_index('ix_stories_importance', 'stories', ['importance'], unique=False)
    op.create_index('ix_stories_payload_gin', 'stories', ['payload'], unique=False, postgresql_using='gin', postgresql_ops={'payload': 'jsonb_path_ops'})
    op.create_table('assets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('bytes_size', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_kind', 'assets', ['kind'], unique=False)
    op.create_index('ix_assets_story_id', 'assets', ['story_id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'format', 'locale', name='uq_content_story_format_locale')
    )
    op.create_index('ix_content_story_id', 'content', ['story_id'], unique=False)
    op.create_table('quality_checks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_checks_status', 'quality_checks', ['status'], unique=False)
    op.create_index('ix_quality_checks_story_id', 'quality_checks', ['story_id'], unique=False)
    op.create_table('renders',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('output', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'output', name='uq_renders_story_output')
    )
    op.create_index('ix_renders_output', 'renders', ['output'], unique=False)
    op.create_index('ix_renders_status', 'renders', ['status'], unique=False)
    op.create_index('ix_renders_story_id', 'renders', ['story_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('terminology', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'target_lang', name='uq_translations_story_lang')
    )
    op.create_index('ix_translations_story_id', 'translations', ['story_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('feed_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_articles_url')
    )
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_source_id', 'articles', ['source_id'], unique=False)
    op.create_index('ix_articles_title_fts', 'articles', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('facts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_article_id', 'facts', ['article_id'], unique=False)
    op.create_index('ix_facts_entity_id', 'facts', ['entity_id'], unique=False)
    op.create_table('story_sources',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'article_id', name='uq_story_sources_story_article')
    )
    op.create_index('ix_story_sources_story_id', 'story_sources', ['story_id'], unique=False)
    op.drop_table('schema_version')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('web_sessions_created_at_idx'), table_name='web_sessions')
    op.drop_index(op.f('web_sessions_user_id_idx'), table_name='web_sessions', postgresql_where='(user_id IS NOT NULL)')
    op.drop_table('web_sessions')
    op.drop_table('categories')
    op.drop_index(op.f('enclosures_entry_id_idx'), table_name='enclosures')
    op.drop_index(op.f('enclosures_user_entry_url_unique_idx'), table_name='enclosures')
    op.drop_table('enclosures')
    op.drop_index(op.f('entry_tombstones_deleted_at_idx'), table_name='entry_tombstones')
    op.drop_table('entry_tombstones')
    op.drop_index(op.f('document_vectors_idx'), table_name='entries', postgresql_using='gin')
    op.drop_index(op.f('entries_feed_id_status_hash_idx'), table_name='entries')
    op.drop_index(op.f('entries_id_user_status_idx'), table_name='entries')
    op.drop_index(op.f('entries_share_code_idx'), table_name='entries', postgresql_where="(share_code <> ''::text)")
    op.drop_index(op.f('entries_user_feed_idx'), table_name='entries')
    op.drop_index(op.f('entries_user_id_status_starred_idx'), table_name='entries')
    op.drop_index(op.f('entries_user_status_changed_idx'), table_name='entries')
    op.drop_index(op.f('entries_user_status_changed_published_idx'), table_name='entries')
    op.drop_index(op.f('entries_user_status_created_idx'), table_name='entries')
    op.drop_index(op.f('entries_user_status_feed_idx'), table_name='entries')
    op.drop_index(op.f('entries_user_status_published_idx'), table_name='entries')
    op.drop_table('entries')
    op.drop_table('acme_cache')
    op.drop_index(op.f('users_google_id_idx'), table_name='users', postgresql_where="(google_id <> ''::text)")
    op.drop_index(op.f('users_openid_connect_id_idx'), table_name='users', postgresql_where="(openid_connect_id <> ''::text)")
    op.drop_table('users')
    op.drop_table('api_keys')
    op.drop_table('integrations')
    op.drop_table('feed_icons')
    op.drop_index(op.f('icons_external_id_idx'), table_name='icons', postgresql_where="(external_id <> ''::text)")
    op.drop_table('icons')
    op.add_column('feeds', sa.Column('source_id', sa.String(length=255), nullable=False))
    op.add_column('feeds', sa.Column('url', sa.String(length=2048), nullable=False))
    op.add_column('feeds', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('feeds', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feeds', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('feeds', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('feeds', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('feeds', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('feeds', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('feeds', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('feeds_feed_id_hide_globally_idx'), table_name='feeds')
    op.drop_index(op.f('feeds_user_category_idx'), table_name='feeds')
    op.drop_constraint(op.f('feeds_user_id_feed_url_key'), 'feeds', type_='unique')
    op.drop_constraint(op.f('feeds_category_id_fkey'), 'feeds', type_='foreignkey')
    op.drop_constraint(op.f('feeds_user_id_fkey'), 'feeds', type_='foreignkey')
    op.create_foreign_key(None, 'feeds', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_column('feeds', 'url_rewrite_rules')
    op.drop_column('feeds', 'last_modified_header')
    op.drop_column('feeds', 'blocklist_rules')
    op.drop_column('feeds', 'checked_at')
    op.drop_column('feeds', 'pushover_priority')
    op.drop_column('feeds', 'cookie')
    op.drop_column('feeds', 'pushover_enabled')
    op.drop_column('feeds', 'apprise_service_urls')
    op.drop_column('feeds', 'crawler')
    op.drop_column('feeds', 'parsing_error_count')
    op.drop_column('feeds', 'rewrite_rules')
    op.drop_column('feeds', 'description')
    op.drop_column('feeds', 'webhook_url')
    op.drop_column('feeds', 'disabled')
    op.drop_column('feeds', 'disable_http2')
    op.drop_column('feeds', 'etag_header')
    op.drop_column('feeds', 'proxy_url')
    op.drop_column('feeds', 'user_id')
    op.drop_column('feeds', 'ignore_http_cache')
    op.drop_column('feeds', 'hide_globally')
    op.drop_column('feeds', 'category_id')
    op.drop_column('feeds', 'keep_filter_entry_rules')
    op.drop_column('feeds', 'fetch_via_proxy')
    op.drop_column('feeds', 'allow_self_signed_certificates')
    op.drop_column('feeds', 'ignore_entry_updates')
    op.drop_column('feeds', 'keeplist_rules')
    op.drop_column('feeds', 'block_filter_entry_rules')
    op.drop_column('feeds', 'user_agent')
    op.drop_column('feeds', 'parsing_error_msg')
    op.drop_column('feeds', 'ntfy_enabled')
    op.drop_column('feeds', 'scraper_rules')
    op.drop_column('feeds', 'password')
    op.drop_column('feeds', 'no_media_player')
    op.drop_column('feeds', 'site_url')
    op.drop_column('feeds', 'username')
    op.drop_column('feeds', 'next_check_at')
    op.drop_column('feeds', 'ntfy_topic')
    op.drop_column('feeds', 'feed_url')
    op.drop_column('feeds', 'ntfy_priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('ntfy_priority', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('feed_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('ntfy_topic', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('next_check_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('site_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('no_media_player', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('scraper_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('ntfy_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('parsing_error_msg', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('user_agent', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('block_filter_entry_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('keeplist_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('ignore_entry_updates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('allow_self_signed_certificates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('fetch_via_proxy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('keep_filter_entry_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('hide_globally', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('ignore_http_cache', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('proxy_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('etag_header', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('disable_http2', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('webhook_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('rewrite_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('parsing_error_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('crawler', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('apprise_service_urls', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('pushover_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('cookie', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('pushover_priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('blocklist_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('last_modified_header', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('url_rewrite_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.create_foreign_key(op.f('feeds_user_id_fkey'), 'feeds', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('feeds_category_id_fkey'), 'feeds', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('feeds_user_id_feed_url_key'), 'feeds', ['user_id', 'feed_url'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('feeds_user_category_idx'), 'feeds', ['user_id', 'category_id'], unique=False)
    op.create_index(op.f('feeds_feed_id_hide_globally_idx'), 'feeds', ['id', 'hide_globally'], unique=False)
    op.alter_column('feeds', 'language',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('feeds', 'title',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('feeds', 'id',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('feeds', 'updated_at')
    op.drop_column('feeds', 'created_at')
    op.drop_column('feeds', 'active')
    op.drop_column('feeds', 'last_checked_at')
    op.drop_column('feeds', 'category')
    op.drop_column('feeds', 'url')
    op.drop_column('feeds', 'source_id')
    op.create_table('icons',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('icons_pkey')),
    sa.UniqueConstraint('hash', name=op.f('icons_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('icons_external_id_idx'), 'icons', ['external_id'], unique=True, postgresql_where="(external_id <> ''::text)")
    op.create_table('feed_icons',
    sa.Column('feed_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('icon_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('feed_icons_feed_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['icon_id'], ['icons.id'], name=op.f('feed_icons_icon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'icon_id', name=op.f('feed_icons_pkey'))
    )
    op.create_table('integrations',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pinboard_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pinboard_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('pinboard_tags', sa.TEXT(), server_default=sa.text("'miniflux'::text"), autoincrement=False, nullable=True),
    sa.Column('pinboard_mark_as_unread', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('instapaper_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('instapaper_username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('instapaper_password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('fever_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('fever_username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('fever_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('wallabag_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('wallabag_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('wallabag_client_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('wallabag_client_secret', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('wallabag_username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('wallabag_password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('nunux_keeper_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('nunux_keeper_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('nunux_keeper_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_chat_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('googlereader_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('googlereader_username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('googlereader_password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('espial_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('espial_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('espial_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('espial_tags', sa.TEXT(), server_default=sa.text("'miniflux'::text"), autoincrement=False, nullable=True),
    sa.Column('linkding_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('linkding_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkding_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('wallabag_only_url', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('matrix_bot_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('matrix_bot_user', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('matrix_bot_password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('matrix_bot_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('matrix_bot_chat_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkding_tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkding_mark_as_unread', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('notion_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('notion_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('notion_page_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('readwise_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('readwise_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('apprise_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('apprise_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('apprise_services_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('shiori_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('shiori_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('shiori_username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('shiori_password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('shaarli_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('shaarli_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('shaarli_api_secret', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('webhook_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('webhook_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('webhook_secret', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_disable_web_page_preview', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_disable_notification', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('telegram_bot_disable_buttons', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('rssbridge_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('rssbridge_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('omnivore_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('omnivore_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('omnivore_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkace_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('linkace_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkace_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkace_tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkace_is_private', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('linkace_check_disabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('linkwarden_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('linkwarden_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkwarden_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('readeck_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('readeck_only_url', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('readeck_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('readeck_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('readeck_labels', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('raindrop_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('raindrop_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('raindrop_collection_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('raindrop_tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('betula_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('betula_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('betula_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('ntfy_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('ntfy_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('ntfy_topic', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('ntfy_api_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('ntfy_username', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('ntfy_password', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('ntfy_icon_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('cubox_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('cubox_api_link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('discord_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('discord_webhook_link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('ntfy_internal_links', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('slack_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('slack_webhook_link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('pushover_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pushover_user', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('pushover_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('pushover_device', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('pushover_prefix', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('rssbridge_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('karakeep_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('karakeep_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('karakeep_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linktaco_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('linktaco_api_token', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linktaco_org_slug', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linktaco_tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linktaco_visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', name='linktaco_link_visibility'), server_default=sa.text("'PUBLIC'::linktaco_link_visibility"), autoincrement=False, nullable=True),
    sa.Column('wallabag_tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('archiveorg_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('karakeep_tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('linkwarden_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('readeck_push_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('integrations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('integrations_pkey'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_keys_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    sa.UniqueConstraint('token', name=op.f('api_keys_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'description', name=op.f('api_keys_user_id_description_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), server_default=sa.text("'en_US'::text"), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.TEXT(), server_default=sa.text("'UTC'::text"), autoincrement=False, nullable=True),
    sa.Column('theme', sa.TEXT(), server_default=sa.text("'light_serif'::text"), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('entry_direction', postgresql.ENUM('asc', 'desc', name='entry_sorting_direction'), server_default=sa.text("'asc'::entry_sorting_direction"), autoincrement=False, nullable=True),
    sa.Column('keyboard_shortcuts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('entries_per_page', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('show_reading_time', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('entry_swipe', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('stylesheet', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('openid_connect_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('display_mode', postgresql.ENUM('fullscreen', 'standalone', 'minimal-ui', 'browser', name='webapp_display_mode'), server_default=sa.text("'standalone'::webapp_display_mode"), autoincrement=False, nullable=True),
    sa.Column('entry_order', postgresql.ENUM('published_at', 'created_at', name='entry_sorting_order'), server_default=sa.text("'published_at'::entry_sorting_order"), autoincrement=False, nullable=True),
    sa.Column('default_reading_speed', sa.INTEGER(), server_default=sa.text('265'), autoincrement=False, nullable=True),
    sa.Column('cjk_reading_speed', sa.INTEGER(), server_default=sa.text('500'), autoincrement=False, nullable=True),
    sa.Column('default_home_page', sa.TEXT(), server_default=sa.text("'unread'::text"), autoincrement=False, nullable=True),
    sa.Column('categories_sorting_order', sa.TEXT(), server_default=sa.text("'unread_count'::text"), autoincrement=False, nullable=False),
    sa.Column('gesture_nav', sa.TEXT(), server_default=sa.text("'tap'::text"), autoincrement=False, nullable=True),
    sa.Column('mark_read_on_view', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('media_playback_rate', sa.NUMERIC(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('block_filter_entry_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('keep_filter_entry_rules', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('mark_read_on_media_player_completion', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('custom_js', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('external_font_hosts', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('always_open_external_links', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('open_external_links_in_new_tab', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('users_openid_connect_id_idx'), 'users', ['openid_connect_id'], unique=True, postgresql_where="(openid_connect_id <> ''::text)")
    op.create_index(op.f('users_google_id_idx'), 'users', ['google_id'], unique=True, postgresql_where="(google_id <> ''::text)")
    op.create_table('acme_cache',
    sa.Column('key', sa.VARCHAR(length=400), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('acme_cache_pkey'))
    )
    op.create_table('entries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feed_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('unread', 'read', 'removed', name='entry_status'), server_default=sa.text("'unread'::entry_status"), autoincrement=False, nullable=True),
    sa.Column('starred', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('comments_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('document_vectors', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('share_code', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('reading_time', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('entries_feed_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('entries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('entries_pkey')),
    sa.UniqueConstraint('feed_id', 'hash', name=op.f('entries_feed_id_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('entries_user_status_published_idx'), 'entries', ['user_id', 'status', 'published_at'], unique=False)
    op.create_index(op.f('entries_user_status_feed_idx'), 'entries', ['user_id', 'status', 'feed_id'], unique=False)
    op.create_index(op.f('entries_user_status_created_idx'), 'entries', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('entries_user_status_changed_published_idx'), 'entries', ['user_id', 'status', 'changed_at', 'published_at'], unique=False)
    op.create_index(op.f('entries_user_status_changed_idx'), 'entries', ['user_id', 'status', 'changed_at'], unique=False)
    op.create_index(op.f('entries_user_id_status_starred_idx'), 'entries', ['user_id', 'status', 'starred'], unique=False)
    op.create_index(op.f('entries_user_feed_idx'), 'entries', ['user_id', 'feed_id'], unique=False)
    op.create_index(op.f('entries_share_code_idx'), 'entries', ['share_code'], unique=True, postgresql_where="(share_code <> ''::text)")
    op.create_index(op.f('entries_id_user_status_idx'), 'entries', ['id', 'user_id', 'status'], unique=False)
    op.create_index(op.f('entries_feed_id_status_hash_idx'), 'entries', ['feed_id', 'status', 'hash'], unique=False)
    op.create_index(op.f('document_vectors_idx'), 'entries', ['document_vectors'], unique=False, postgresql_using='gin')
    op.create_table('entry_tombstones',
    sa.Column('feed_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("hash <> ''::text", name=op.f('entry_tombstones_hash_check')),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('entry_tombstones_feed_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'hash', name=op.f('entry_tombstones_pkey'))
    )
    op.create_index(op.f('entry_tombstones_deleted_at_idx'), 'entry_tombstones', ['deleted_at'], unique=False)
    op.create_table('enclosures',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('media_progression', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('enclosures_entry_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('enclosures_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('enclosures_pkey'))
    )
    op.create_index(op.f('enclosures_user_entry_url_unique_idx'), 'enclosures', ['user_id', 'entry_id', sa.literal_column("encode(sha256(url::bytea), 'hex'::text)")], unique=True)
    op.create_index(op.f('enclosures_entry_id_idx'), 'enclosures', ['entry_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hide_globally', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('categories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('user_id', 'title', name=op.f('categories_user_id_title_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('web_sessions',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('secret_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.CheckConstraint("jsonb_typeof(state) = 'object'::text", name=op.f('web_sessions_state_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('web_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('web_sessions_pkey'))
    )
    op.create_index(op.f('web_sessions_user_id_idx'), 'web_sessions', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('web_sessions_created_at_idx'), 'web_sessions', ['created_at'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('handle', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('cred_id', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('attestation_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('aaguid', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('sign_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('clone_warning', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('added_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_seen_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('backup_eligible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('backup_state', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('webauthn_credentials_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('handle', name=op.f('webauthn_credentials_pkey')),
    sa.UniqueConstraint('cred_id', name=op.f('webauthn_credentials_cred_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('schema_version',
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_index('ix_story_sources_story_id', table_name='story_sources')
    op.drop_table('story_sources')
    op.drop_index('ix_facts_entity_id', table_name='facts')
    op.drop_index('ix_facts_article_id', table_name='facts')
    op.drop_table('facts')
    op.drop_index('ix_articles_title_fts', table_name='articles', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_articles_source_id', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_translations_story_id', table_name='translations')
    op.drop_table('translations')
    op.drop_index('ix_renders_story_id', table_name='renders')
    op.drop_index('ix_renders_status', table_name='renders')
    op.drop_index('ix_renders_output', table_name='renders')
    op.drop_table('renders')
    op.drop_index('ix_quality_checks_story_id', table_name='quality_checks')
    op.drop_index('ix_quality_checks_status', table_name='quality_checks')
    op.drop_table('quality_checks')
    op.drop_index('ix_content_story_id', table_name='content')
    op.drop_table('content')
    op.drop_index('ix_assets_story_id', table_name='assets')
    op.drop_index('ix_assets_kind', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_stories_payload_gin', table_name='stories', postgresql_using='gin', postgresql_ops={'payload': 'jsonb_path_ops'})
    op.drop_index('ix_stories_importance', table_name='stories')
    op.drop_index('ix_stories_created_at', table_name='stories')
    op.drop_table('stories')
    op.drop_table('sources')
    op.drop_table('entities')
    # ### end Alembic commands ###
